# Generated by Django 5.1.3 on 2024-11-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(max_length=75, verbose_name='Nombre')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha Modificación')),
                ('estado', models.BooleanField(default=True, verbose_name='Categoria Activa/No Activa')),
            ],
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado Activo/Inactivo')),
            ],
            options={
                'verbose_name': 'Lector',
                'verbose_name_plural': 'Lectores',
            },
        ),
    ]
