# Generated by Django 5.1.3 on 2024-11-29 19:46

import django.db.models.deletion
import django_quill.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', django_quill.fields.QuillField()),
                ('fecha_publicacion', models.DateField(auto_now_add=True, verbose_name='Fecha Publicación')),
                ('imagen', models.ImageField(blank=True, upload_to='publicaciones', verbose_name='Imagen')),
                ('estado', models.BooleanField(default=True, verbose_name='Publicación Activa/No Activa')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_blog.categoria')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
            },
        ),
        migrations.CreateModel(
            name='ComentarioLector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('fecha_publicacion', models.DateField(auto_now_add=True, verbose_name='Fecha Publicación')),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_blog.lector')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_blog.publicacion')),
            ],
            options={
                'verbose_name': 'Comentario Lector',
                'verbose_name_plural': 'Comentarios Lector',
            },
        ),
        migrations.CreateModel(
            name='ComentarioAutor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('fecha_publicacion', models.DateField(auto_now_add=True, verbose_name='Fecha Publicación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_blog.publicacion')),
            ],
            options={
                'verbose_name': 'Comentario Autor',
                'verbose_name_plural': 'Comentarios Autor',
            },
        ),
    ]
