# Generated by Django 5.1.3 on 2024-12-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0002_publicacion_comentariolector_comentarioautor'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='descripcion',
            field=models.CharField(blank=True, default='Descripción de la publicación', max_length=75, verbose_name='Descripción'),
        ),
    ]
